version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - ./BackEnd/db_migrate/init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "kyjstream"
    ports:
      - 3307:3306

  mongodb:

    image: mongo:4.4
    restart: always    
    environment:
      MONGO_INITDB_DATABASE : "kyjstream"
      MONGO_INITDB_ROOT_USERNAME : ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD  : ${MONGO_PASSWORD}
    ports:
      - 27017:27017

  backend:
    build: backend
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - mongodb
  frontend:
    build: ./frontend/KYJstream
    ports:
      - 4200:4200
    volumes:
      - ./FrontEnd/KYJstream:/app
      - /app/node_modules
volumes:
  db-data: